<a href="https://colab.research.google.com/github/vishalakshi-19/ML_Week1/blob/main/mlpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("harpartapsingh13/student-burnout-and-dropout-risk-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'student-burnout-and-dropout-risk-dataset' dataset.
Path to dataset files: /kaggle/input/student-burnout-and-dropout-risk-dataset

In [4]:
csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
df = pd.read_csv(os.path.join(path, csv_files[0]))

In [5]:
df.head()

,Student_ID,Age,Gender,Year_of_Study,Department,Residence_Type,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,...,Family_Income_Bracket,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score,Counseling_Access,Burnout_Level,Dropout_Risk
0,STU00001,23,Female,2,Science,Hostel,93.0,4.1,7.13,2.0,...,Upper-Middle,5.5,10.0,4.0,NaN,7.0,NaN,No,Low,No
1,STU00002,20,Female,4,Engineering,Day Scholar,94.3,0.0,10.00,0.0,...,Low,3.7,4.0,5.5,5.1,9.3,2.8,Yes,Medium,Yes
2,STU00003,24,Male,2,Business,PG/Rented,61.2,2.6,8.02,0.0,...,Middle,4.8,8.1,9.0,5.2,5.7,5.4,No,High,Yes
3,STU00004,21,Female,4,Medicine,Hostel,66.9,3.1,5.34,1.0,...,Lower-Middle,7.0,6.6,2.8,4.2,5.1,3.9,No,High,Yes
4,STU00005,23,Female,1,Engineering,NaN,84.8,2.9,4.45,1.0,...,Lower-Middle,1.3,7.3,0.9,6.4,8.1,5.1,No,Low,No

In [7]:
df.sample(10)

,Student_ID,Age,Gender,Year_of_Study,Department,Residence_Type,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,...,Family_Income_Bracket,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score,Counseling_Access,Burnout_Level,Dropout_Risk
575,STU00576,25,Male,2,NaN,Hostel,81.3,3.4,8.60,1.0,...,Low,3.5,7.0,4.3,3.0,7.3,7.4,No,Low,No
33,STU00034,25,Male,1,Arts,PG/Rented,64.6,3.9,6.63,1.0,...,Middle,9.9,7.6,4.1,5.1,7.2,3.8,Yes,Low,Yes
429,STU00430,25,NaN,3,Science,PG/Rented,67.1,3.1,8.13,0.0,...,Low,4.0,9.2,9.3,2.8,NaN,1.0,No,Medium,Yes
288,STU00289,19,Male,2,Science,PG/Rented,61.6,3.3,7.20,0.0,...,Upper-Middle,2.8,9.6,NaN,5.0,5.7,4.5,No,Medium,Yes
526,STU00527,19,Male,2,Business,Day Scholar,94.8,7.1,5.91,0.0,...,Lower-Middle,2.2,3.4,7.1,6.2,5.5,7.0,No,Medium,Yes
716,STU00717,20,Other,1,Science,Day Scholar,100.0,1.9,4.81,0.0,...,Lower-Middle,6.2,8.0,6.1,2.5,5.9,3.7,No,Low,No
604,STU00605,17,Male,3,Business,Hostel,41.6,2.9,5.84,0.0,...,Middle,5.4,7.1,3.0,8.8,4.0,5.4,Yes,High,Yes
53,STU00054,22,Female,3,Medicine,Hostel,69.5,2.3,4.91,1.0,...,Middle,1.6,6.2,4.2,3.7,6.4,2.8,No,Medium,Yes
230,STU00231,22,Female,4,Science,PG/Rented,83.7,3.4,6.26,0.0,...,Lower-Middle,2.7,8.3,3.0,5.8,4.1,5.6,No,Medium,Yes
463,STU00464,19,Female,1,Business,Hostel,NaN,4.6,3.87,0.0,...,Middle,7.5,8.8,8.9,4.9,5.9,3.7,No,Medium,Yes

In [8]:
df.isnull().sum()

Student_ID                 0
Age                        0
Gender                    30
Year_of_Study              0
Department                23
Residence_Type            17
Attendance_Percent        51
Study_Hours_Per_Day       35
Previous_GPA              35
Backlogs                  15
Sleep_Hours               35
Screen_Time_Hours         36
Exercise_Freq_Per_Week     0
Social_Activity_Score     40
Part_Time_Job             25
Family_Income_Bracket     13
Financial_Stress_Score    43
Family_Support_Score      44
Stress_Level              49
Anxiety_Score             39
Motivation_Score          41
Peer_Pressure_Score       41
Counseling_Access          0
Burnout_Level              0
Dropout_Risk               0
dtype: int64

In [16]:
df.drop(df['Student_ID'])

KeyError: "['STU00001', 'STU00002', 'STU00003', 'STU00004', 'STU00005', 'STU00006', 'STU00007', 'STU00008', 'STU00009', 'STU00010', 'STU00011', 'STU00012', 'STU00013', 'STU00014', 'STU00015', 'STU00016', 'STU00017', 'STU00018', 'STU00019', 'STU00020', 'STU00021', 'STU00022', 'STU00023', 'STU00024', 'STU00025', 'STU00026', 'STU00027', 'STU00028', 'STU00029', 'STU00030', 'STU00031', 'STU00032', 'STU00033', 'STU00034', 'STU00035', 'STU00036', 'STU00037', 'STU00038', 'STU00039', 'STU00040', 'STU00041', 'STU00042', 'STU00043', 'STU00044', 'STU00045', 'STU00046', 'STU00047', 'STU00048', 'STU00049', 'STU00050', 'STU00051', 'STU00052', 'STU00053', 'STU00054', 'STU00055', 'STU00056', 'STU00057', 'STU00058', 'STU00059', 'STU00060', 'STU00061', 'STU00062', 'STU00063', 'STU00064', 'STU00065', 'STU00066', 'STU00067', 'STU00068', 'STU00069', 'STU00070', 'STU00071', 'STU00072', 'STU00073', 'STU00074', 'STU00075', 'STU00076', 'STU00077', 'STU00078', 'STU00079', 'STU00080', 'STU00081', 'STU00082', 'STU00083', 'STU00084', 'STU00085', 'STU00086', 'STU00087', 'STU00088', 'STU00089', 'STU00090', 'STU00091', 'STU00092', 'STU00093', 'STU00094', 'STU00095', 'STU00096', 'STU00097', 'STU00098', 'STU00099', 'STU00100', 'STU00101', 'STU00102', 'STU00103', 'STU00104', 'STU00105', 'STU00106', 'STU00107', 'STU00108', 'STU00109', 'STU00110', 'STU00111', 'STU00112', 'STU00113', 'STU00114', 'STU00115', 'STU00116', 'STU00117', 'STU00118', 'STU00119', 'STU00120', 'STU00121', 'STU00122', 'STU00123', 'STU00124', 'STU00125', 'STU00126', 'STU00127', 'STU00128', 'STU00129', 'STU00130', 'STU00131', 'STU00132', 'STU00133', 'STU00134', 'STU00135', 'STU00136', 'STU00137', 'STU00138', 'STU00139', 'STU00140', 'STU00141', 'STU00142', 'STU00143', 'STU00144', 'STU00145', 'STU00146', 'STU00147', 'STU00148', 'STU00149', 'STU00150', 'STU00151', 'STU00152', 'STU00153', 'STU00154', 'STU00155', 'STU00156', 'STU00157', 'STU00158', 'STU00159', 'STU00160', 'STU00161', 'STU00162', 'STU00163', 'STU00164', 'STU00165', 'STU00166', 'STU00167', 'STU00168', 'STU00169', 'STU00170', 'STU00171', 'STU00172', 'STU00173', 'STU00174', 'STU00175', 'STU00176', 'STU00177', 'STU00178', 'STU00179', 'STU00180', 'STU00181', 'STU00182', 'STU00183', 'STU00184', 'STU00185', 'STU00186', 'STU00187', 'STU00188', 'STU00189', 'STU00190', 'STU00191', 'STU00192', 'STU00193', 'STU00194', 'STU00195', 'STU00196', 'STU00197', 'STU00198', 'STU00199', 'STU00200', 'STU00201', 'STU00202', 'STU00203', 'STU00204', 'STU00205', 'STU00206', 'STU00207', 'STU00208', 'STU00209', 'STU00210', 'STU00211', 'STU00212', 'STU00213', 'STU00214', 'STU00215', 'STU00216', 'STU00217', 'STU00218', 'STU00219', 'STU00220', 'STU00221', 'STU00222', 'STU00223', 'STU00224', 'STU00225', 'STU00226', 'STU00227', 'STU00228', 'STU00229', 'STU00230', 'STU00231', 'STU00232', 'STU00233', 'STU00234', 'STU00235', 'STU00236', 'STU00237', 'STU00238', 'STU00239', 'STU00240', 'STU00241', 'STU00242', 'STU00243', 'STU00244', 'STU00245', 'STU00246', 'STU00247', 'STU00248', 'STU00249', 'STU00250', 'STU00251', 'STU00252', 'STU00253', 'STU00254', 'STU00255', 'STU00256', 'STU00257', 'STU00258', 'STU00259', 'STU00260', 'STU00261', 'STU00262', 'STU00263', 'STU00264', 'STU00265', 'STU00266', 'STU00267', 'STU00268', 'STU00269', 'STU00270', 'STU00271', 'STU00272', 'STU00273', 'STU00274', 'STU00275', 'STU00276', 'STU00277', 'STU00278', 'STU00279', 'STU00280', 'STU00281', 'STU00282', 'STU00283', 'STU00284', 'STU00285', 'STU00286', 'STU00287', 'STU00288', 'STU00289', 'STU00290', 'STU00291', 'STU00292', 'STU00293', 'STU00294', 'STU00295', 'STU00296', 'STU00297', 'STU00298', 'STU00299', 'STU00300', 'STU00301', 'STU00302', 'STU00303', 'STU00304', 'STU00305', 'STU00306', 'STU00307', 'STU00308', 'STU00309', 'STU00310', 'STU00311', 'STU00312', 'STU00313', 'STU00314', 'STU00315', 'STU00316', 'STU00317', 'STU00318', 'STU00319', 'STU00320', 'STU00321', 'STU00322', 'STU00323', 'STU00324', 'STU00325', 'STU00326', 'STU00327', 'STU00328', 'STU00329', 'STU00330', 'STU00331', 'STU00332', 'STU00333', 'STU00334', 'STU00335', 'STU00336', 'STU00337', 'STU00338', 'STU00339', 'STU00340', 'STU00341', 'STU00342', 'STU00343', 'STU00344', 'STU00345', 'STU00346', 'STU00347', 'STU00348', 'STU00349', 'STU00350', 'STU00351', 'STU00352', 'STU00353', 'STU00354', 'STU00355', 'STU00356', 'STU00357', 'STU00358', 'STU00359', 'STU00360', 'STU00361', 'STU00362', 'STU00363', 'STU00364', 'STU00365', 'STU00366', 'STU00367', 'STU00368', 'STU00369', 'STU00370', 'STU00371', 'STU00372', 'STU00373', 'STU00374', 'STU00375', 'STU00376', 'STU00377', 'STU00378', 'STU00379', 'STU00380', 'STU00381', 'STU00382', 'STU00383', 'STU00384', 'STU00385', 'STU00386', 'STU00387', 'STU00388', 'STU00389', 'STU00390', 'STU00391', 'STU00392', 'STU00393', 'STU00394', 'STU00395', 'STU00396', 'STU00397', 'STU00398', 'STU00399', 'STU00400', 'STU00401', 'STU00402', 'STU00403', 'STU00404', 'STU00405', 'STU00406', 'STU00407', 'STU00408', 'STU00409', 'STU00410', 'STU00411', 'STU00412', 'STU00413', 'STU00414', 'STU00415', 'STU00416', 'STU00417', 'STU00418', 'STU00419', 'STU00420', 'STU00421', 'STU00422', 'STU00423', 'STU00424', 'STU00425', 'STU00426', 'STU00427', 'STU00428', 'STU00429', 'STU00430', 'STU00431', 'STU00432', 'STU00433', 'STU00434', 'STU00435', 'STU00436', 'STU00437', 'STU00438', 'STU00439', 'STU00440', 'STU00441', 'STU00442', 'STU00443', 'STU00444', 'STU00445', 'STU00446', 'STU00447', 'STU00448', 'STU00449', 'STU00450', 'STU00451', 'STU00452', 'STU00453', 'STU00454', 'STU00455', 'STU00456', 'STU00457', 'STU00458', 'STU00459', 'STU00460', 'STU00461', 'STU00462', 'STU00463', 'STU00464', 'STU00465', 'STU00466', 'STU00467', 'STU00468', 'STU00469', 'STU00470', 'STU00471', 'STU00472', 'STU00473', 'STU00474', 'STU00475', 'STU00476', 'STU00477', 'STU00478', 'STU00479', 'STU00480', 'STU00481', 'STU00482', 'STU00483', 'STU00484', 'STU00485', 'STU00486', 'STU00487', 'STU00488', 'STU00489', 'STU00490', 'STU00491', 'STU00492', 'STU00493', 'STU00494', 'STU00495', 'STU00496', 'STU00497', 'STU00498', 'STU00499', 'STU00500', 'STU00501', 'STU00502', 'STU00503', 'STU00504', 'STU00505', 'STU00506', 'STU00507', 'STU00508', 'STU00509', 'STU00510', 'STU00511', 'STU00512', 'STU00513', 'STU00514', 'STU00515', 'STU00516', 'STU00517', 'STU00518', 'STU00519', 'STU00520', 'STU00521', 'STU00522', 'STU00523', 'STU00524', 'STU00525', 'STU00526', 'STU00527', 'STU00528', 'STU00529', 'STU00530', 'STU00531', 'STU00532', 'STU00533', 'STU00534', 'STU00535', 'STU00536', 'STU00537', 'STU00538', 'STU00539', 'STU00540', 'STU00541', 'STU00542', 'STU00543', 'STU00544', 'STU00545', 'STU00546', 'STU00547', 'STU00548', 'STU00549', 'STU00550', 'STU00551', 'STU00552', 'STU00553', 'STU00554', 'STU00555', 'STU00556', 'STU00557', 'STU00558', 'STU00559', 'STU00560', 'STU00561', 'STU00562', 'STU00563', 'STU00564', 'STU00565', 'STU00566', 'STU00567', 'STU00568', 'STU00569', 'STU00570', 'STU00571', 'STU00572', 'STU00573', 'STU00574', 'STU00575', 'STU00576', 'STU00577', 'STU00578', 'STU00579', 'STU00580', 'STU00581', 'STU00582', 'STU00583', 'STU00584', 'STU00585', 'STU00586', 'STU00587', 'STU00588', 'STU00589', 'STU00590', 'STU00591', 'STU00592', 'STU00593', 'STU00594', 'STU00595', 'STU00596', 'STU00597', 'STU00598', 'STU00599', 'STU00600', 'STU00601', 'STU00602', 'STU00603', 'STU00604', 'STU00605', 'STU00606', 'STU00607', 'STU00608', 'STU00609', 'STU00610', 'STU00611', 'STU00612', 'STU00613', 'STU00614', 'STU00615', 'STU00616', 'STU00617', 'STU00618', 'STU00619', 'STU00620', 'STU00621', 'STU00622', 'STU00623', 'STU00624', 'STU00625', 'STU00626', 'STU00627', 'STU00628', 'STU00629', 'STU00630', 'STU00631', 'STU00632', 'STU00633', 'STU00634', 'STU00635', 'STU00636', 'STU00637', 'STU00638', 'STU00639', 'STU00640', 'STU00641', 'STU00642', 'STU00643', 'STU00644', 'STU00645', 'STU00646', 'STU00647', 'STU00648', 'STU00649', 'STU00650', 'STU00651', 'STU00652', 'STU00653', 'STU00654', 'STU00655', 'STU00656', 'STU00657', 'STU00658', 'STU00659', 'STU00660', 'STU00661', 'STU00662', 'STU00663', 'STU00664', 'STU00665', 'STU00666', 'STU00667', 'STU00668', 'STU00669', 'STU00670', 'STU00671', 'STU00672', 'STU00673', 'STU00674', 'STU00675', 'STU00676', 'STU00677', 'STU00678', 'STU00679', 'STU00680', 'STU00681', 'STU00682', 'STU00683', 'STU00684', 'STU00685', 'STU00686', 'STU00687', 'STU00688', 'STU00689', 'STU00690', 'STU00691', 'STU00692', 'STU00693', 'STU00694', 'STU00695', 'STU00696', 'STU00697', 'STU00698', 'STU00699', 'STU00700', 'STU00701', 'STU00702', 'STU00703', 'STU00704', 'STU00705', 'STU00706', 'STU00707', 'STU00708', 'STU00709', 'STU00710', 'STU00711', 'STU00712', 'STU00713', 'STU00714', 'STU00715', 'STU00716', 'STU00717', 'STU00718', 'STU00719', 'STU00720', 'STU00721', 'STU00722', 'STU00723', 'STU00724', 'STU00725', 'STU00726', 'STU00727', 'STU00728', 'STU00729', 'STU00730', 'STU00731', 'STU00732', 'STU00733', 'STU00734', 'STU00735', 'STU00736', 'STU00737', 'STU00738', 'STU00739', 'STU00740', 'STU00741', 'STU00742', 'STU00743', 'STU00744', 'STU00745', 'STU00746', 'STU00747', 'STU00748', 'STU00749', 'STU00750', 'STU00751', 'STU00752', 'STU00753', 'STU00754', 'STU00755', 'STU00756', 'STU00757', 'STU00758', 'STU00759', 'STU00760', 'STU00761', 'STU00762', 'STU00763', 'STU00764', 'STU00765', 'STU00766', 'STU00767', 'STU00768', 'STU00769', 'STU00770', 'STU00771', 'STU00772', 'STU00773', 'STU00774', 'STU00775', 'STU00776', 'STU00777', 'STU00778', 'STU00779', 'STU00780', 'STU00781', 'STU00782', 'STU00783', 'STU00784', 'STU00785', 'STU00786', 'STU00787', 'STU00788', 'STU00789', 'STU00790', 'STU00791', 'STU00792', 'STU00793', 'STU00794', 'STU00795', 'STU00796', 'STU00797', 'STU00798', 'STU00799', 'STU00800'] not found in axis"

In [14]:
df['Part_Time_Job']

0      Yes
1      Yes
2       No
3      Yes
4       No
      ...
795     No
796    Yes
797     No
798     No
799    Yes
Name: Part_Time_Job, Length: 800, dtype: object

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [10]:
x_train,x_test,y_train,y_test= train_test_split(df.drop('Dropout_Risk',axis=1),df['Dropout_Risk'],test_size=0.2,random_state=42)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.pipeline import make_pipeline,Pipeline
from sklearn.impute import SimpleImputer

In [ ]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['Attendance_Percentage'],[]),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')